import sys
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv('/opt/renewal-automation-system/.env')
sys.path.insert(0, '/opt/renewal-automation-system')

from src.email_outreach.gmail_client import GmailRenewalClient

def send_alert(subject: str, message: str, to_email: str = 'carlo@streetsmart.insurance'):
    try:
        client = GmailRenewalClient()
        if not client.is_authenticated():
            print('Gmail client not authenticated')
            return False
        res = client.send_email(
            to_email=to_email,
            subject=subject,
            body_text=message,
            html_body=f'''
            <div style="font-family: Arial, sans-serif; padding: 20px; border: 1px solid #e0e0e0; border-radius: 8px; max-width: 600px;">
                <h2 style="color: #d32f2f; margin-top: 0;">🚨 Robie System Alert</h2>
                <p style="font-size: 15px; color: #333;"><strong>Host:</strong> hermes-poc-01 (e2-standard-8)</p>
                <div style="background: #fff3f3; padding: 15px; border-left: 4px solid #d32f2f; margin: 15px 0;">
                    <pre style="margin: 0; font-family: monospace; white-space: pre-wrap;">{message}</pre>
                </div>
                <p style="font-size: 13px; color: #777; margin-bottom: 0;">Automated alert generated by Robie Autonomous Health Watchdog.</p>
            </div>
            '''
        )
        print('Alert sent successfully:', res.get('id', 'sent'))
        return True
    except Exception as e:
        print('Error sending alert email:', e)
        return False

if __name__ == '__main__':
    subj = sys.argv[1] if len(sys.argv) > 1 else 'Robie Test Alert'
    msg = sys.argv[2] if len(sys.argv) > 2 else 'This is a test notification.'
    send_alert(subj, msg)
